MIN_SLEEP_SECS = 2
MAX_SLEEP_SECS = 5
RING_TIME = 10
PORTAL_OPEN_MAX_SECS = 30
MSECS_PER_FRAME = 4
ADD_STATIC_TO_IMAGE = True
ALARM_SOUND_FILE = 'sleigh-bells.mp3'
SANTA_PORTAL_VIDEO_FILE = 'SantaPortal2.mp4'
